### ISSUE TITLE
Checklist: normalise topics

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/java#1656]
**Note**: the suggestions are generated automagically. If something is _actually_ missing, please open an issue at [problem-specifications](https://github.com/exercism/problem-specifications) to add the missing topics.

```
=> fetching config from ../exercism-java/config.json
=> reading topics from ..\problem-specifications\TOPICS.txt
```

<details>
  <summary>List of valid topics</summary>

  - `abstract_classes`
  - `callbacks`
  - `conditionals`
  - `events`
  - `equality`
  - `exception_handling`
  - `generics`
  - `inheritance`
  - `interfaces`
  - `loops`
  - `operator_overloading`
  - `pattern_matching`
  - `polymorphism`
  - `recursion`
  - `threading`
  - `type_conversion`
  - `variables`
  - `arrays`
  - `booleans`
  - `classes`
  - `dates`
  - `discriminated_unions`
  - `enumerations`
  - `floating_point_numbers`
  - `graphs`
  - `integers`
  - `lists`
  - `maps`
  - `matrices`
  - `optional_values`
  - `queues`
  - `records`
  - `sequences`
  - `sets`
  - `stacks`
  - `strings`
  - `structs`
  - `time`
  - `trees`
  - `tuples`
  - `algorithms`
  - `bitwise_operations`
  - `concurrency`
  - `cryptography`
  - `domain_specific_languages`
  - `files`
  - `filtering`
  - `games`
  - `globalization`
  - `logic`
  - `math`
  - `memory_management`
  - `networking`
  - `parallelism`
  - `parsing`
  - `pattern_recognition`
  - `performance`
  - `randomness`
  - `refactoring`
  - `regular_expressions`
  - `searching`
  - `security`
  - `sorting`
  - `text_formatting`
  - `transforming`
  - `behavior_driven_development`
  - `functional_programming`
  - `object_oriented_programming`
  - `reactive_programming`
  - `test_driven_development`
</details>

## Exercises with non-standard topics

- [ ] [`dnd-character`](https://github.com/exercism/java/tree/master/exercises/dnd-character)
  Incorrect topics:
  - [ ] `game` (perhaps: `games`)
- [ ] [`sublist`](https://github.com/exercism/java/tree/master/exercises/sublist)
  Incorrect topics:
  - [ ] `enumeration` (perhaps: `enumerations`)
- [ ] [`zipper`](https://github.com/exercism/java/tree/master/exercises/zipper)
  Incorrect topics:
  - [ ] `integer` (perhaps: `integers`)
  - [ ] `links` (perhaps: `lists`, `loops`, `files`, `events`, `dates`, `maps`, `sets`, `stacks`, `strings`, `time`, `trees`, `games`, `logic`, `arrays`, `classes`, `graphs`, `queues`, `tuples`, `math`)
  - [ ] `nodes` (perhaps: `loops`, `dates`, `trees`, `files`, `games`, `lists`, `maps`, `queues`, `sets`, `time`, `tuples`, `logic`, `events`, `arrays`, `booleans`, `classes`, `graphs`, `integers`, `records`, `stacks`, `math`)  
  - [ ] `tree` (perhaps: `trees`)
- [ ] [`pythagorean-triplet`](https://github.com/exercism/java/tree/master/exercises/pythagorean-triplet)
  Incorrect topics:
  - [ ] `integer` (perhaps: `integers`)

## Exercises without topics

- [ ] [`accumulate`](https://github.com/exercism/java/tree/master/exercises/accumulate)
- [ ] [`binary`](https://github.com/exercism/java/tree/master/exercises/binary)
- [ ] [`hexadecimal`](https://github.com/exercism/java/tree/master/exercises/hexadecimal)
- [ ] [`octal`](https://github.com/exercism/java/tree/master/exercises/octal)
- [ ] [`strain`](https://github.com/exercism/java/tree/master/exercises/strain)
- [ ] [`trinary`](https://github.com/exercism/java/tree/master/exercises/trinary)

**Comment by FridaTveit** [comment]
Thanks @SleeplessByte! 🙂 The exercises without topics are all deprecated so no need to add topics to them I believe 🙂

**Comment by SleeplessByte** [comment]
@FridaTveit my quick script indeed does not filter out deprecated exercises 😅 .

**Comment by jmrunkle** [comment]
If this is as simple as I think it is, I'll take a stab at it.

**Comment by SleeplessByte** [comment]
It really is that simple :)
