### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/java#1873]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/java/issues/1864)
- [x] [Add key features](https://github.com/exercism/java/issues/1865)
- [x] [Add tags](https://github.com/exercism/java/issues/1866)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/java/issues/1867)
- [x] [Update status of track](https://github.com/exercism/java/issues/1871)
- [x] [Update status of Concept Exercises](https://github.com/exercism/java/issues/1872)
- [x] [Pass linting checks](https://github.com/exercism/java/issues/1868)
- [x] [Build Test Runner](https://github.com/exercism/java/issues/1869)
- [x] [Build Analyzer and Representer](https://github.com/exercism/java/issues/1870) (optional)
- [ ] [Add blurb to Concept Exercises](https://github.com/exercism/java/issues/1897)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by mirkoperillo** [comment]
v3 has been released
